- tutorials/daily_logs.md
Made some minor changes in Daily Logs tutorial to test authoring in md and making PRs.
> making test commit to fix minor errors in Daily Logs tutorial

- _data/navigation.yml
- tutorials/tutorial_e_signature_integration.md
New integration guide requested by Partnerships team covering e-signature solutions. See https://procoretech.atlassian.net/browse/DOCS-243 for background information.
> DOCS-243 New integration guide for developing e-signature solutions

- README.md
Updating and expanding readme file to be more informative to non-developer contributors, such as internal Procore technical writers.
> DOCS-256 readme updates

- tools/sdk.md
Reformatting and updating sdk page to have separate sections for the JavaScript SDK and JavaScript Sample Application.
> DOCS-221 Updates to SDK page

- tools/sdk.md
Adding bulleted formatting for consistency.
> DOCS-221 Followup

- _data/navigation.yml
- best_practices/api_call_sequencing.md
New best practices guide for call sequencing in installations.
> DOCS-208 API call sequencing and app installation

- tutorials/tutorial_uploads.md
Adding a link to Create Project File ref doc in the bulleted list at bottom of page.
> DOCS-266 Add Create Project File endpoint to list

- tutorials/filtering_on_list_actions.md
Adding filter array syntax and example. Also fixed a syntax bug in another example.
> DOCS-262 Filter array syntax/example

- erp_integration/erp_access.md
> DOCS-353 grammar fix

- tutorials/tutorial_user_permissions.md
Added links to support site permissions page.
> DOC-214 tool permissions update 

- oauth/oauth_endpoints.md
https://procoretech.atlassian.net/browse/ZL-1365
Remove cURL command that will not work and link to documentation explaining how to use the endpoint instead.
> Zl 1365 update oauth documentation

- tutorials/tutorial_correspondence.md
Adding initial section for webhooks. To be expanded in next iterations.
> DOCS-449 Correspondence webhooks support

- api_essentials/api_security_overview.md
- building_applications/developer_managed_service_accounts.md
- overview/introduction.md
- overview/service_account_deprecation.md
> fixing typos

- overview/partner_content_reqs.md
Add a new section to the Marketplace Requirements page (https://developers.procore.com/documentation/partner-content-reqs) covering the Regions tab.
> DOCS-439 Document new Regions tab.

- overview/partner_content_reqs.md
Changing 'supported' to 'available'.
> DMX-2960 'supported' to 'available'

- _data/navigation.yml
- getting_started/rest_api_overview.md
- overview/introduction.md
- overview/vapid_deprecation.md
- tutorials/tutorial_change_orders.md
Updates for vapid sunset:
- Added new banner content
- Removed vapid deprecation article from left nav
- Fixed misc examples
> DOCS-469, 470 Vapid sunset 

- _layouts/default.html
- assets/css/nav.css
- assets/js/nav.js
JIRA: https://procoretech.atlassian.net/browse/AGX-695
Makes docs viewable on mobile
https://user-images.githubusercontent.com/4781472/152896587-58f5560c-f1d1-4c3a-908a-b412a3418e65.mov
> [AGX-695] fix docs on mobile

- tutorials/tutorial_config_fieldsets.md
https://procoretech.atlassian.net/browse/WKF-2437
An integrator was having issues updating a project multi select custom field. We thought it'd be a good idea to add an example of that in the docs.
> [WKF] Add example of multi select cfs update

- assets/css/nav.css
- assets/js/nav.js
adds hideNav query param to add styles when query param passed as needed in the Iframe in https://github.com/procore/dev-portal/pull/2605
<details>
<summary>No Query Param</summary>
</details>
<details>
<summary>With Query Param</summary>
</details>
> [AGX-705] add hideNav query param

- tutorials/tutorial_wbs.md
> DOCS-477 WBS dev guide

- tutorials/tutorial_wbs.md
> DOCS-481 missing link

- tutorials/tutorial_wbs.md
Adding section on managing segment items.
> DOCS-489 segment items section

- _layouts/default.html
- building_applications/building_apps_define_manifest.md
Made code blocks scroll, fixed manifest line.
> DOCS-457 manifest line break

- api_essentials/restful_api_concepts.md
Fixed wording for codes 409 and 429.
> DOCS-484 status code descriptions

- _data/navigation.yml
- building_applications/building_apps_helper_library.md
Updates to iframe helper library article as requested by partner integration managers.
> DOCS-512 Updated Embedded App Helper Page

- building_applications/building_apps_helper_library.md
Fixing case issues in examples as spotted by API Support.
> DOCS-507 iframe library examples incorrect

- best_practices/mpz_headers.md
- building_applications/developer_managed_service_accounts.md
Updates based on feedback from partners and internal stakeholders.
> DOCS-472 DMSA dev guide udpates

- building_applications/developer_managed_service_accounts.md
Updates to FAQ section for retrieving a list of companies in which a given DMSA application is installed.
> DOCS-522 DMSA guide FAQ update

- overview/introduction.md
Adding new banner for access token requirement.
> DOCS-503 fas banner

- best_practices/mpz_headers.md
- overview/introduction.md
Adding banner and updating mpz header page per Product
> DOCS-526  banner for Procore-Company-Id header

- tutorials/tutorial_config_fieldsets.md
Adding note about unsupported tools.
> DOCS-533 Update configurable fieldsets article

- other_procore_apis/bim_web_viewer.md
> [BIM-Webviewer] Document Zoom Extents API

- tutorials/tutorial_wbs.md
Updating WBS codes section to cover the 'Update a WBS Code' and 'Bulk update WBS codes' endpoints recently released by the WBS team.
> DOCS-536 WBS update endpoints

- building_applications/developer_managed_service_accounts.md
Added new faq on determining project access. Documented two call sequences for DMSA bot user and logged in user respectively
> DOCS-545 DMSA guide updates

- other_procore_apis/bim_web_viewer.md
It's the first time we've directly referenced a version in the docs. Thought this might be nice to have. A non-trivial nice-to-have beyond this would be versioned docs, but I don't think we're they're yet 😅
> [BIM-Webviewer] Update Docs for Space Junk Elimination

- overview/announcements.md
Added announcement for dev sandbox drawing and spec upload issue
> DOCS-557 Issue with drawing and spec uploads in dev sandbox envs

- building_applications/building_apps_maximizing_conversion_rates.md
Adding heading links to front of page as requested by Product.
> DOCS-549 Add header links to relevant article sections

- getting_started/making_first_call.md
Changing SSL reference to TLS in 'Making Your First Call' page.
> DOCS-437 change SSL to TLS

- other_procore_apis/bim_web_viewer.md
> [BIM-Webviewer] Add migration guides for v3 to v4 and v4 to v5

- building_applications/building_apps_define_manifest.md
> Fix missing underscore typo

- _layouts/default.html
- assets/css/nav.css
- assets/js/nav.js
- search.json
Implementing article search in nav bar
> Docs 570 dev portal investigate open source search libraries for docs site

- building_applications/developer_managed_service_accounts.md
Updates to DMSA article based on customer feedback/request
> DOCS-585 service account and DMSA security content improvements

- api_essentials/api_security_overview.md
- building_applications/developer_managed_service_accounts.md
- overview/announcements.md
- overview/service_account_deprecation.md
Updating deprecation banner per Product.
> DOCS-585 service account deprecation banner

- overview/announcements.md
Updating announcement text as requested by P&T
> DOCS-596 update text in upload issue announcement

- overview/partner_overview.md
Need to add a first step which is to submit the partner application
> Add partner application as first step

- overview/partner_content_reqs.md
Add a prerequisites section for partner signup and agreement, as requested by partner integration managers.
> DOCS-595 add prereqs section

- _data/navigation.yml
Adding new use cases section in left nav as requested by the Partner integration managers.
> DOCS-560 new use cases section in left nav toc

- erp_integration/erp_events_dictionary.md
- erp_integration/erp_staged_records.md
> Erp 2527/update reset payment payload

- oauth/oauth_access_tokens.md
Updated link to point to correct article.
> DOCS-572 fixed incorrect link in oauth access tokens

- overview/announcements.md
Removing announcement for Drawing and Specification Uploads per development team.
> DOCS-659 remove announcement

- erp_integration/erp_staged_records.md
> ERP: Update metadata key from tab to configs

- overview/announcements.md
Adding announcement for the change to the monthly sandbox refresh schedule.
> DOCS-672 new announcement for change to refresh timing 

- bim_webviewer/bim_web_viewer.md
Added getRootObject documentation to our model namespace.
> [BIM-2426]Added model.getRootObject documentation

- bim_webviewer/bim_web_viewer.md
Added getNumObjects documentation to our model namespace.
> [BIM-2428]Added model.getNumObjectsSelected documentation

- bim_webviewer/bim_web_viewer.md
> [BIM-2427] Adds documentation for the new GUI namespace in the bim viewer.

- bim_webviewer/bim_web_viewer.md
Added api namespace to the documentation
Added getNamesForObject documentation to api namespace
> [BIM-2429]Added getNamesForObject documentation

- bim_webviewer/bim_web_viewer.md
> [BIM-2474] Update docs for objectSelect, objectDeselect, and selectedUpdated

- bim_webviewer/bim_web_viewer.md
Added documentation for the following
`model.setXRayMode()`
`model.setNormalMode()`
`model.setNavigationMode()`
`model.setMeasurement()`
> [BIM-2519] Added documentation for setting navigation modes, measurement, and rendering modes

- bim_webviewer/bim_web_viewer.md
Added `hideAllObjects` to our `model` namespace.
> [BIM-2526] Added `model.hideAllObjects` documentation

- tutorials/tutorial_workflows.md
Links to workflows reference docs were broken in tutorial, corrected.
> Corrected broken links

- erp_integration/erp_events_dictionary.md
https://procoretech.atlassian.net/browse/ERP-2961
Adding ERP contract payments docuemtns
> ERP-2958 adding ERP contract payment documents

- overview/announcements.md
Add an announcement entry for the May 18th int-sbx maintenance (db upgrade)
> [no-ticket] Add an announcement for the May 18th int-sbx maintenance (db upgrade)

- bim_webviewer/bim_web_viewer.md
> [BIM-2834] `getSnapshotDataUrl` documentation

- overview/announcements.md
New announcement for file link URL schema change.
> DOCS-719 file link URL change

- bim_webviewer/bim_web_viewer.md
Merge after https://github.com/procore/bim-webviewer/pull/943 is released
> Add section box and xray mode tools to tool section

- bim_webviewer/bim_web_viewer.md
> [BIM-2899] `getObjects` minor update

- overview/announcements.md
> DOCS-707 access token announcement

- additional_resources/faq.md
Updating token expiration information in the faq page.
> DOCS-707 Updating token expiration information

- _data/navigation.yml
- building_applications/building_side_panel_apps.md
Changing title of the side panel doc to “Building Procore Side Panel Applications”
> DOCS-733 update title for side panel doc

- building_applications/building_side_panel_apps.md
Vendors is misspelled in the key, confirmed the key value is correct in the side panel yaml
> Fix typo in key

- building_applications/building_side_panel_apps.md
Adding new views as implemented in DMX-3969.
> DOCS-736 new view keys for side panel

- erp_integration/erp_external_data_details.md
fixing broken link to API reference page
> DOCS-740 broken link in ERP docs

- tutorials/tutorial_uploads.md
> Fixed typo in Direct File Uploads tutorial

- bim_webviewer/bim_web_viewer.md
> [BIM-3078] `camera.getSnapshot` and `camera.getSnapshotDataUrl` migration guide

- bim_webviewer/bim_web_viewer.md
🎫 https://procoretech.atlassian.net/browse/BIM-3344 🎫
> [BIM-3344] Add docs for `camera.setMarkup`

- webhooks/webhooks.md
Jira ticket: [AGX-2386](https://procoretech.atlassian.net/browse/AGX-2386)
Title ☝️ 
[AGX-2386]: https://procoretech.atlassian.net/browse/AGX-2386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> updating webhooks docs to reflect V2 changes.

- tutorials/tutorial_budget_changes_api.md
Added banner and updated code samples and table to clarify that comments to adjustment line id 1 are accepted, all subsequent are discarded.
> DOCS-742 Budget Changes updates

- _data/navigation.yml
- best_practices/secure_file_access_tips.md
- overview/announcements.md
Adding new best practices article for secure file access tips per confluence article "[Adding new best practices article for secure file access tips](https://procoretech.atlassian.net/l/cp/5SCV2Vj7)".
> DOCS-744 secure file access tips

- bim_webviewer/bim_web_viewer.md
Adding new events to our list of possible events to subscribe to as a third party. These were previously undocumented.
> added new events for project settings events

- overview/announcements.md
Added a draft announcement for service account sunset timeline to the announcements page in the dev docs.
> DMX-4117 service account sunset timeline

- building_applications/building_side_panel_apps.md
Updating supported side panel views to be in conformance with the latest version of the presence.yml file.
> DOCS-745 Side panel view updates

- overview/service_account_deprecation.md
Adding sunset banner to previous deprecation article.
> DMX-4117 update service account deprecation article

- building_applications/building_side_panel_apps.md
Updating postMessage example to account for multiple procore regions.
> DMX-4140 update postMessage example in side panel doc

- bim_webviewer/bim_web_viewer.md
> [BIM-3738] Document `gui.setToolbarHidden(hidden)` method in gui namespace

- bim_webviewer/bim_web_viewer.md
> [BIM-3736] Document `gui.setHotkeysEnabled(enabled)` method in gui namespace

- bim_webviewer/bim_web_viewer.md
> [BIM-3758] Migration Guide: v10 to v11 

- bim_webviewer/bim_web_viewer.md
Migration Guide
Options updated
Required options!
If model revision (not all pictured)
If file extraction
> [BIM-3644] Migration Guide update + Options updates

- bim_webviewer/bim_web_viewer.md
> [BIM-3387] Documentation for `setPose` SDK method

- bim_webviewer/bim_web_viewer.md
> [BIM-2909] Migration guide for type declarations and updated return types on some methods

- getting_started/development_environments.md
Updating content around monthly sandbox refresh timing. Changes based on discussion in cs-tech-services-api slack channel... https://procoretech.slack.com/archives/C1WK13BRD/p1712092030486269
> DOCS-748 updating monthly sandbox refresh timing content

- building_applications/building_side_panel_apps.md
Fixed mismatched routes in https://github.com/procore/procore/pull/122985 so I wanted to update the documentation.
> [NO TICKET] fixes mismatch routes & views for commitments.requisitions

- building_applications/building_side_panel_apps.md
Update with additional supported side panel views as implemented by https://procoretech.atlassian.net/browse/DMX-4364
> DOCS-750 Update table of supported side panel views

- getting_started/making_first_call.md
Updated URL for OAuth tokens in code samples on making your first call page.
> Updated code samples to reflect updated oauth token URL

- overview/partner_overview.md
Updated text and email per prod specialists.
> DOCS-752 Marketplace QA team contact info change

- building_applications/building_side_panel_apps.md
RE: https://github.com/procore/procore/pull/124267
> [DMX-4376] add Commitments MFE routes

- oauth/oauth_keys.md
Added note to top section of page stating that dynamic redirect URIs are not supported per request in CEDT-783
> Added note stating dynamic URIs are not supported

- bim_webviewer/bim_web_viewer.md
🎫 https://procoretech.atlassian.net/browse/BIM-4171 🎫 
🎫 https://procoretech.atlassian.net/browse/BIM-4172 🎫
> [BIM-4171/BIM-4172] `model.get/setVisibility` and `model.get/setRenderMode`

- tutorials/tutorial_correspondence.md
Fixed links that weren't pointing to the right spot in the reference docs, also fixed broken image reference.
> Fixed links

- building_applications/building_side_panel_apps.md
Updated the side panel dev guide to include supported views for the Incidents tool.
> DOCS-758 adding supported views for Incidents

- tutorials/tutorial_financial_tools.md
Updated description of location of commitment setting.
> DOCS-760 commitment setting location update

- getting_started/development_environments.md
Noted opt-in requirement, and location of opt-in toggle
> Added note about opt-in requirement for monthly sandbox

- tutorials/tutorial_uploads.md
Fixed typo reported in CEDT-812
> CEDT-812 Fixed typo

- oauth/oauth_introduction.md
Hiding section for Postman collection
> Hiding section for Postman collection

- _data/navigation.yml
- overview/new_rest_v2_version.md
initial draft version for review
> AGX-2736 rest v2 intro page

- bim_webviewer/bim_web_viewer.md
Documentation for https://github.com/procore/bim-webviewer/pull/1244
> [BIM-4223] `Webviewer` accepts new `resources` option

- bim_webviewer/bim_web_viewer.md
🎫 https://procoretech.atlassian.net/browse/BIM-4709 🎫
> [BIM-4709] Add v15 to v16 migration guide

- resources/object_model_project.md
Fixed broken link in object-model-project file
> Fixed broken link to ref docs for Direct Costs

- bim_webviewer/bim_web_viewer.md
🎫 https://procoretech.atlassian.net/browse/BIM-4705 🎫
> [BIM-4705] Document `gui.showCoachmark` and `gui.hideCoachmark`

- erp_integration/erp_metadata_details.md
This PR adds docs about the new ERP Metadata configuration for custom WBS segments.
> add docs on custom_wbs_segments

- building_applications/developer_managed_service_accounts.md
Added new section on DMSA permissions best practices.
> DOCS-767 update DMSA guide with permissions best practices

- building_applications/building_side_panel_apps.md
Added the 'uk01' zone in the postMessage code example. Additional text on supporting multiple zones.
> DMX-4579 update postmessage example

- api_essentials/api_security_overview.md
- building_applications/developer_managed_service_accounts.md
- overview/announcements.md
- overview/service_account_deprecation.md
Updating sunset dates for traditional service accounts based on input from Product.
> DOCS-771 traditional service account sunset dates

- getting_started/development_environments.md
Updating the table of sandbox refresh dates for 2025.
> DOCS-772 sandbox 2025 dates

- bim_webviewer/bim_web_viewer.md
🎫 https://procoretech.atlassian.net/browse/BM-1229 🎫 
- Add v16 to v17 migration guide section
- Update `getGlobalOffset` description section to `getGlobalOffsetDoNotUse` and add dummy-link to preserve links to `#get-global-offset`
- Update Migrating to World Coordinates section to `getGlobalOffsetDoNotUse`
> [BM-1229] Add v16 to v17 migration guide and update `model.getGlobalOffsetDoNotUse` documentation

- overview/announcements.md
Updating sunset date for Traditional Service Accounts to March 18, 2025 on Announcements page.
> DOCS-773 sunset date update

- getting_started/development_environments.md
Updating sandbox cutover date table.
> Updating sandbox cutover date table

- tutorials/tutorial_workflows_v2.md
Updating Workflows V2 tutorial for new endpoints.
I missed that the new webhook endpoints aren't public yet so we'll have to let customers know that they have to reach out for info.
> [WKF-4783] Update endpoint and rewrite some content for workflows v2 api tutorial

- announcements/service_account_deprecation.md
- api_essentials/api_security_overview.md
- building_applications/developer_managed_service_accounts.md
- webhooks/webhooks_api.md
Updating Dates for Service Account Sunset and Webhook Info.
> DOCS-776 misc content updates

- best_practices/api_call_sequencing.md
Article updates related to the change to Allow User Installs defaulting to Off.
> PI-8699 article updates

- app_marketplace/procore_partner_overview.md
Fixing duplicate text on the Marketplace & Partner Overview
> Fixing small issue with duplicate text

- getting_started/development_environments.md
Updating July cutover date to 07/08
> Updating July cutover date to 07/08

- app_marketplace/procore_partner_overview.md
Adding 1 link to the general partnership page and that's it
> Adding a new link to the partner section

- building_applications/side_panel_view_keys.md
Updating Side Panel Page to include perma link (link is broken currently) and fix wrap styling
> Updating side panel page for text wrap style and permalink

- api_essentials/rate_limiting.md
updated rate limiting docs to incldue details about spike limit and future 503s
> Pdc rate limiting docs
