- _data/navigation.yml
- erp_integration/erp_external_data_details.md
https://procoretech.atlassian.net/browse/ERP-1378
We want to provide integrators with more information about how to use the External Data API, specifically about what Procore Types our External Data API supports. This commit adds an "External Data Details" page with this information, nested under the tab for ERP Integration docs.
> [ERP-1378] Add External Data Details page to ERP Integration tab

- overview/partner_content_reqs.md
- overview/partner_support_content_reqs.md
- overview/partner_tech_reqs.md
These pages existed in the previous version of the repository but had not
been ported over due to the fact that they are not linked in the sidebar.
Closes #11
> Add missing Partner pages

- _data/navigation.yml
- additional_resources/faq.md
- getting_started/development_environments.md
- getting_started/making_first_call.md
The goal of this project is to document Procore API and how to use it.
There are several pages in which we make reference to Postman and link to its website and snippets, for instance:
- https://github.com/procore/documentation/blob/main/additional_resources/faq.md#testing
- https://github.com/procore/documentation/blob/main/getting_started/making_first_call.md#curl-and-postman
- https://github.com/procore/documentation/blob/main/oauth/oauth_introduction.md#procore-oauth-20-postman-collection-with-curl-examples
These references are helpful enough for developers to check Postman if they are interested. 
However, having an entire page about Postman itself goes beyond the scope of this project.
By removing a page that is not the *focus* of this project, we make it easier for developers to …
> ✂️  Remove Postman page

- _data/navigation.yml
The message of this page is that, when a Procore API endpoint asks for a `country_code` or a `state_code` parameter, they should be supplied following the Alpha-2 of the ISO-3166 specification.
This page also lists all the endpoints that expect those parameters, and the reference of each one of those endpoints already specified the correct format, e.g.:
Therefore, there is no need for someone browsing the API reference to reach out for a separate guide page, since the information they need about the format of the string is already present in the reference page.
> ✂️  Remove Country Code pages

- overview/introduction.md
- overview/vapid_deprecation.md
Adding the sunset date for the Vapid API as requested by Ecosystem Product. See JIRA https://procoretech.atlassian.net/browse/DOCS-248 for additional information.
> Adding sunset date for Vapid API

- tutorials/tutorial_timecard_entries.md
Update to Introduction section to include a sentence about not needing Field Productivity in order to integrate with third-party time tracking applications.
> DOCS-238 Update Intro section

- oauth/oauth_installed_apps.md
Fixing code example in refresh token step to use a request body rather than query parameters.
> DOCS-264 OAuth example fix

- oauth/oauth_choose_grant_type.md
- oauth/oauth_endpoints.md
Clarifying duration/expiration of auth code in the oauth 2.0 authorization code grant flow.
> DOCS-236 Auth code duration/expiration

- tutorials/tutorial_direct_drawing_uploads.md
Added a section on the [`Working with Direct Drawing Uploads`](https://developers.procore.com/documentation/tutorial-direct-drawing-uploads) page. It provides explanatory information about how to work with `drawing_id` for automatic drawing review and the support for multi-sheet drawings.
https://procoretech.atlassian.net/browse/DP-299
> [DP-299] Add section for working with drawing_id

- other_procore_apis/bim_web_viewer.md
**Which issue #** https://procoretech.atlassian.net/browse/BIM-1376
Release v1.4.0 of the Webviewer SDK introduced new events and a new tool third parties to use.
* Added two new events ('isolateCompleted' | 'hideSimilarCompleted') to our events table
* Added `VIEW_PROPERTIES` to our Tools table
* Looks like some auto changes from linting
``` 
/
+-- other_procore_apis
M     +-- bim_web_viewer.md
```
New events added to the events table
New Tool added to the tools table
> BIM-1376 Update Webviewer SDK Documentation : New events and tool

- api_essentials/pagination.md
Updates to pagination guide including...
- Reviewed 'non' supported endpoints list and tested in Postman.
- Removed List Checklists endpoint as it now supports pagination.
- Removed List Most Recent Images endpoint as it is set as an 'internal' endpoint in Rest v1.
- Minor formatting fixes.
> DOCS-473 Pagination Guide updates

- README.md
- _layouts/default.html
- other_procore_apis/bim_web_viewer.md
This PR :
- adds the ability to add a link character next to `h2`, `h3`, and `h4` tags (`##`, `###`, and `####`) that links to that heading, which I'm dubbing as "Heading Links" for lack of a known name. This functionality is opt-in and available across all documentation pages
- adds info on how to use Heading Links to README
- adds these Heading Links to select headings in the BIM Webviewer API page.
- fixes a couple incorrect-seeming headers on the BIM Webviewer API page.
Basically the same feature exists on the Rest API side of things (e.g. https://developers.procore.com/reference/rest/v1/bim-file-extractions?version=1.0#show-bim-file-extraction), but I wasn't sure how to utilize that.
https://user-images.githubusercontent.com/2865469/154759471-9560faf8-90ba-41a8-9285-a39879030309.mov …
> [BIM] Add Header Links To Webviewer Doc

- other_procore_apis/bim_web_viewer.md
https://github.com/procore/bim-webviewer/pull/540 adds a LOADING tool to [@procore/bim-webviewer-sdk](https://www.npmjs.com/package/@procore/bim-webviewer-sdk). 
This PR updates the docs to reflect that. It should go out on April 20 when we publish those changes.
It also alphabetizes the tools list. Previously it didn't seem like there was any particular order to them.
> [BIM] Add Loading Tool to BIM Webviewer Doc

- other_procore_apis/bim_web_viewer.md
https://github.com/procore/bim-webviewer/pull/570 adds `camera.zoomExtents(bbox)` to [@procore/bim-webviewer-sdk](https://www.npmjs.com/package/@procore/bim-webviewer-sdk). 
This PR updates the docs to reflect that. It should go out on May 19 when we publish those changes.
> [BIM] Add `camera.zoomExtents(bbox)` to BIM Webviewer Doc

- other_procore_apis/bim_web_viewer.md
Web Viewer already supports `accessToken` and `baseUrl` options but they were undocumented. This documents them in the Options section and adds some details on how to retrieve access an access token and how you might use the base url. It also removes some old options and declares our codeblocks as `js` for syntax highlighting in editors and github.
- Document `accessToken` option
- Document `baseUrl` option
- Remove documentation of `version` option
- Remove documentation of `swUrl` option
- Remove documentation of `swEnable` option
- Remove documentation of `swScope` option
> [BIM] Add `accessToken` and `baseUrl`

- _data/navigation.yml
- erp_integration/erp_staged_records.md
This PR adds a Developer guide for the Staged Records feature of the ERP platform. The goal is to describe the nuanced behavior of the API as well as document requirements across the various item types that are supported.
> ERP-1979: Create Staged Records guide

- erp_integration/erp_events_dictionary.md
Link to Jira issue: https://procoretech.atlassian.net/browse/ERP-1978
Our ERP Events Dictionary is missing a handful of events, and it's also difficult to read through since it's mostly just a wall of text. We'd like to give integrators better documentation to make it easier for them to integrate with our platform. This PR reformats the page for (hopefully) improved readability and adds the events we're missing. Some of the major changes are listed below.
- Cutting out unnecessary API examples and replacing them with links to the relevant API documentation instead.
- Adding tables that provide a quick overview of the events available for each entity type.
- Making the events in the dictionary linkable via anchor tags (e.g. adding `#sync_vendors` to the end of the URL).
- Adding …
> [ERP-1978] Reformat and extend ERP events dictionary

- other_procore_apis/bim_web_viewer.md
We got a [comment from a dev at a third-party partner Inertia](https://procore-external.slack.com/archives/C01T2SGTEKB/p1658943944795329) about installation and reminded me that our installation docs are a little outdated so this updates them.
> [BIM] Update BIM Webviewer Docs on Installation

- building_applications/building_apps_manage_collabs.md
Added section covering steps for giving a collaborator access to sandbox company.
> DOCS-518 update covering collaborator access to sandbox company

- tutorials/tutorial_drawings.md
Removing sample code in Drawings Tutorial as it uses implicit auth, which is no longer supported.
> DOCS-520 remove sample code with implicit auth

- other_procore_apis/bim_web_viewer.md
- Updates docs for methods renamed in https://github.com/procore/bim-webviewer/pull/672
- Adds docs for `model.getMeshnodeFromObjectId` (formerly `model.getObjectFromPropertyId` which was undocumented).
- Adds a migration guides section
> [BIM-Webviewer] SDK Method Renames and Migration Guide

- other_procore_apis/bim_web_viewer.md
The link button was pointing to the wrong url and lead to a 404. This PR fixes that.
>  [BIM-Webviewer] Fix Links for Zoom Extents Methods

- bim_webviewer/bim_web_viewer.md
Added `getObjects` documentation to our `model` namespace.
> [BIM-2511] Added `model.getObjects` documentation

- bim_webviewer/bim_web_viewer.md
Added new events `windowOpen` and `windowClose` to our `events` namespace.
> [BIM-2430] Added `windowOpen` and `windowClose` events to documentation

- bim_webviewer/bim_web_viewer.md
Added new event `animate` which was previously not documented, as well as documented the payload it will have.
> [BIM-2581] Animate payload event documentation

- building_applications/building_apps_define_manifest.md
We have a missing comma in the example manifest
> Fix missing comma

- getting_started/development_environments.md
Added a new table of projected monthly sandbox refresh dates at the request of API Support.
Also, broke out bulleted sections into individual lines for better change/diff tracking in the future.
> DOCS-732 new table listing projected monthly sandbox refresh dates

- bim_webviewer/bim_web_viewer.md
Documented new event 
- `objectTreeUpdated`
Documented new SDK methods 
- `api.filterObjects` 
- `model.filterObjectTree` 
- `model.clearObjectTreeFilter`
Updated methods that now take an optional `objectTreeName` 
- `model.getObject`
- `model.getObjects`
- `model.getRootObject`
- `model.hideObjects`
- `model.hideAllObjects`
- `model.unhideObjects`
- `model.selectObjects`
- `model.deselectObjects`
- `model.selectAllObjects`
> [BIM-3107] Object Trees Documentation

- getting_started/making_first_call.md
Adding some clarification on grant type to the cURL calls as requested by API Support.
> DOCS-725 clarify grant type

- oauth/oauth_access_tokens.md
Adding a content block to the OAuth Access Token article to explain the planned reduction in token expiration time, and document approaches developers can take to handle token expiration/refresh.
> DOCS-737 planned reduction of token expiration time

- building_applications/building_side_panel_apps.md
Updating the postMessage example code to be more explicit with the `targetOrigin` parameter, reducing the chance for security problems caused from a dev cutting/pasting the sample code verbatim into their project.
> DOCS-738 Update postMessage method example code

- bim_webviewer/bim_web_viewer.md
Documents the updates that occurred in v9.1.0: 
```md
- Add new SDK methods and events to control the section box display
- new method: `model.configureSectionBoxDisplay` - sets state for how the section box display will appear
- new method: `model.toggleSectionBoxDisplay` - turns on/off the section box display feature, respecting the configuration set by `configureSectionBoxDisplay`
- changed method: `model.setSectionBox` - now takes a fourth argument `showCoachmark` which is a boolean that determines whether the "Sectioning Applied" coachmark is shown when the section box is set. Defaults to true, which was was the behavior before when it was not exposed as an argument.
- Full signature now looks like: `model.setSectionBox(min: Vector3, max: Vector3, rotation: Vector3, showCoachmark?: …
```
> [BIM-3366] Document Section Box Display Methods and Events

- bim_webviewer/bim_web_viewer.md
This is tied to this change: https://github.com/procore/bim-webviewer/pull/1065
---
The migration guide basically was the same as in v7 to v8 in that you need to potentially deal with coordinate system changes. I tried to extract this into one section: "Migrating to World Coordinates". The v7 to v8 section as well as the new v9 to v10 section now links to that. We will likely have more of these types of changes in the future.
> [BIM-3498] Migration Guide for `intersectPointClick` Change

- bim_webviewer/bim_web_viewer.md
It's no longer used and the REST API will eventually stop returning it.
> [BIM-3523] Remove References to `cellUrl`

- getting_started/development_environments.md
Updating the monthly sandbox refresh time to mid-afternoon eastern, per feedback from tech services.
> DOCS-743 update the sandbox refresh time

- bim_webviewer/bim_web_viewer.md
Mainly updating this to document these changes that add a new "survey" mode https://github.com/procore/bim-webviewer/pull/1119, but also reworded the current documentation to show all the supported modes.
> [BIM-3729] Document all modes supported by `setNavigationMode`

- bim_webviewer/bim_web_viewer.md
- Adds new `markup` namespace section
- Adds docs for `markup` namespace methods:
- `markup.clear`
- `markup.draw`
- `markup.drawAnchored`
- `markup.setRedlines`
- Marks `camera.setMarkup` as deprecated and points to `markup.setRedlines` docs
> [BIM-3608] Markup Namespace Methods

- bim_webviewer/bim_web_viewer.md
> [BIM-3495] Add migration guide for methods/events that return `bbox` in world coordinates

- bim_webviewer/bim_web_viewer.md
Forgot to document these methods 😵‍💫
I also moved the analogous `getNumObjectsSelected` to be collocated with selection methods. It was in a kind of random place it felt before.
> [BIM-3878] Document `resetSectionBox`, `getNumObjectsHidden`, `getSectionBoxDisplay` added in v12.0.0

- bim_webviewer/bim_web_viewer.md
Associated with https://github.com/procore/bim-webviewer/pull/1185
> [BIM-4042] `model.getViewpoint` and `model.setViewpoint`

- webhooks/webhooks_api.md
AGX-2873 
Defined namespace requirements in documentation don't precisely match the allowed values.  Update the documentation to notify customers of what values are truly accepted.  Specifically, digits 0-9 are allowed.
> update namespace requirements and fix typo

- getting_started/rest_api_overview.md
- webhooks/webhooks_api.md
Add sunset pill to documentation in dev portal. 
TODO
The documentation contains an image of the pills in the dev portal that will need to be updated in the future to include sunset when the dev portal changes are implemented.
A couple small changes that were in my local changes from before around webhooks.
> Agx 2972/documentation changes sunsetting

- getting_started/development_environments.md
Updating the September sandbox refresh date to account for the Labor Day holiday.
> DOCS-765 sandbox cutover date change

- erp_integration/erp_staged_records.md
This PR adds examples of the support fields we accept when staging records for import.
> Staged Record Docs [Update]: add item type data examples

- bim_webviewer/bim_web_viewer.md
> [BIM-4795] Unit Formatting Methods

- api_essentials/rate_limiting.md
Updated header table with x-rate-limit-reset with time unit.
> DOCS-769 add time unit to header table

- Gemfile
- Gemfile.lock
Using `ruby 3.1.6p260 (2024-05-29 revision a777087be6) [x64-mingw-ucrt]`, Jekyll serve fails on Ruby 3+ (https://github.com/jekyll/jekyll/issues/8523)
> added webrick to Gemfile

- tutorials/tutorial_uploads.md
Update API documentation to reflect use of upload_id.
This PR updates the API documentation to fully document the upload_id approach for file uploads.
This aligns with our broader effort to migrate away from NFS-based file uploads to the more performant, reliable S3 direct upload methodology. 
- Added documentation for using `upload_id` with various endpoints (Action Plans, Meeting Topics)
- Added examples showing proper usage of `upload_id` in API requests and responses
- Included migration recommendations for developers still using legacy approaches
- Emphasized performance and reliability improvements with the `upload_id` approach
- Added new documentation section explaining the `upload_id` concept and implementation
- Added specific examples showing proper request and response formats …
> PPC2-4815: update upload doc

- api_essentials/rate_limiting.md
- app_marketplace/listing_your_app.md
- app_marketplace/procore_partner_overview.md
- app_marketplace/update_your_marketplace_app.md
- platform_concepts/federal_zone_overview.md
- Adding content to the FedRAMP document but keeping it UNLISTED for now, until we have the 'Deploy/Go-Live'. This is just to generate feedback.
- Updating Partner Content in anticipation of their Partner Program update for 2025
Updates include:
1. Highlighting differences between FedRAMP and Commercial
2. Adding new Partner Items to existing document and reworking the 'Manange and Improve' section
> Adding FedRAMP content and updating Partner Content

- _includes/app_marketplace_legal_disclaimer.md
- _includes/need_help_section.md
- app_marketplace/listing_your_app.md
- app_marketplace/market_your_app.md
- app_marketplace/marketplace_checklist.md
- app_marketplace/marketplace_listing_guidelines.md
- app_marketplace/marketplace_requirements.md
- app_marketplace/procore_partner_overview.md
- app_marketplace/update_your_marketplace_app.md
- platform_concepts/federal_zone_overview.md
- Updating FedRAMP documents per internal feedback (keeping as an unlisted asset/resource) for the time being.
- Small changes to the Partner Docs, including adding the _includes references to template/common items.
> Updating FedRAMP Docs per feedback and some changes to Partner Items
